name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 : Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-north-1'

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      # Step 4: Install dependencies
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "FastAPI/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"


      # Step 5: Package app
      - name: Package FastAPI application
        run: |
           mkdir deployment-package
           cp -r FastAPI/requirements.txt/* deployment-package/
           cp lambda_function.py deployment-package/
           cd deployment-package
           zip -r ../lambda_function.zip .

      # Step 6 Deploy
      - name: Deploy to AWS Lambda
        run: |
              aws lambda update-function-code \
              --function-name fastapi-app \
              --zip-file fileb://lambda_function.zip
                
      

#      # Step 6: Deploy 1 11    12
#      - name: Deploy to AWS Lambda
#        run: |
#          source venv/bin/activate
#          zappa deploy dev
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: 'eu-west-1'
